### ISSUE TITLE
[Firebase Crash Report] In App Web View is crashing for some users on Android

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#254]
**Describe the bug**
On firebase, there is an application crash logged by ~200 users. Here is the issue log:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{ca.etsmtl.applets.etsmobile/com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to read from field 'com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeSafariBrowserManager.plugin' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**To Reproduce**
Need to be figured out, probably it's by opening a quicklink in ÉTS tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/25663435/138106790-92142296-51d5-48b3-8d29-8e5d0f919f85.png)

**Smartphone (please complete the following information):**
This is only happening on android devices.

**Additional context**
[This issue](https://github.com/pichillilorenzo/flutter_inappwebview/issues/379) from the package inAppWebView, mention it but it seems to be already fixed so we might have to follow up with the maintainer.

**Comment by apomalyn** [comment]
Dans ce cas, l'erreur ne devrait pas être fire dans crashlytics
