### ISSUE TITLE
Error while loading data from secure storage

### ISSUE THREAD

**Issue by MysticFragilist** [ApplETS/Notre-Dame#692]
**Describe the bug**
When accessing data from the phone, a user can't load his data due to an unknown exception. While looking on Firebase I found the specific log for this error.

The error log on crashlytics:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
	at w2.b.b(StorageCipher18Implementation.java:7)
	at v2.d.m(FlutterSecureStoragePlugin.java:2)
	at v2.d.t(FlutterSecureStoragePlugin.java:2)
	at v2.d.f(FlutterSecureStoragePlugin.java:1)
	at v2.d$b.run(FlutterSecureStoragePlugin.java:25)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null). Error thrown getPassword - PlatformException - PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
	at w2.b.b(StorageCipher18Implementation.java:7)
	at v2.d.m(FlutterSecureStoragePlugin.java:2)
	at v2.d.t(FlutterSecureStoragePlugin.java:2)
	at v2.d.f(FlutterSecureStoragePlugin.java:1)
	at v2.d$b.run(FlutterSecureStoragePlugin.java:25)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null).
       at MX.RKc(rbi:607)
       at VX._gbe(ubi:167)
       at LAa.ywf(Coi:312)
       at zBa.EAf(npi:105)
       at zBa.DAf(npi:52)
```

**To Reproduce**
N/A

**Expected behavior**
The app should load data properly.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 7 pro (could be other devices)
 - OS: Android 31
 - Version 

**Additional context**
I found a thread that could help find a solution: https://github.com/mogol/flutter_secure_storage/issues/354

**Comment by MysticFragilist** [comment]
This was fix in #387 , the issue mentionned in discord for the user was unrelated to this. closing
